### ISSUE TITLE
Bridge Port Type attribute description typo

### ISSUE THREAD

**Issue by Yuji-2022** [BroadbandForum/device-data-model#1]
Hi, 

I think the description for the attribute Bridging.Bridge.i.Port.i.Type contains the following error : 

    ProviderNetworkPort (Indicates this Port is an S-TAG aware port of a ProviderBridge)
    CustomerNetworkPort (Indicates this Port is an S-TAG aware port of a ProviderBridge)
    CustomerEdgePort (Indicates this Port is an C-TAG aware port of a ProviderBridge)
    CustomerVLANPort (Indicates this Port is an C-TAG aware port of a Customer Bridge)
    VLANUnawarePort (Indicates this Port is a VLAN unaware member of an 802.1D-2004 bridge) 

the second line should be : 
CustomerNetworkPort (Indicates this Port is an S-TAG aware port of a Customer Bridge)

**Comment by wlupton** [comment]
Thank you for bringing this to our attention. We've reviewed this and don't think that it's an error. Here's a comparison of what both TR-181 and the 802.1Q-2011 MIB say about these values (I've bolded some text):

Term | TR-181 | MIB
-- | -- | --
ProviderNetworkPort | S-TAG aware port of a ProviderBridge | S-tag aware port of a Provider Bridge or Backbone Edge Bridge used for connections **within a PBN or PBBN**
CustomerNetworkPort | S-TAG aware port of a ProviderBridge | S-tag aware port of a Provider Bridge or Backbone Edge Bridge used for connections **to the exterior of a PBN or PBBN**
CustomerEdgePort | C-TAG aware port of a ProviderBridge | C-tag aware port of a Provider Bridge used for connections **to the exterior of a PBN or PBBN**
CustomerVLANPort | C-TAG aware port of a Customer Bridge | C-tag aware port of an **enterprise VLAN aware bridge**
VLANUnawarePort | VLAN unaware member of an 802.1D-2004 bridge |  

So the problem with the CustomerNetworkPort line is not that it should say "Customer Bridge" but that it's not as specific as the MIB.

We could clarify this, or we could rely on the "Provider" versus "Customer" names to imply "within PBN/PBBN" (provider) and "exterior of PBN/PBBN" (customer). What do you think?

**Comment by Yuji-2022** [comment]
Thank you for the explanation, indeed it is more explicit in MIB definition.

From what I understand it depends whether we refer to a  **Provider Bridge** or  **Provider Edge Bridge** 

So I think it will be better to clarify the description rather than using "Provider" vs "Customer" names.

**Comment by wlupton** [comment]
Hello. We've decided not to make any changes. Thanks for your comment, and for the discussion!
