### ISSUE TITLE
Math formulae of Device.MQTT.Client.{i}.ConnectRetryTime are wrongly rendered

### ISSUE THREAD

**Issue by anderewrey** [BroadbandForum/device-data-model#2]
In the HTML document of https://usp-data-models.broadband-forum.org/tr-181-2-17-0-usp.html, the description of the [ConnectRetryTimer](https://usp-data-models.broadband-forum.org/tr-181-2-17-0-usp.html#D.Device:2.Device.MQTT.Client.ConnectRetryTime) parameter is wrong: because of the superscript markdown, the formatting is applied over too much text, instead of simply the math formula itself.

Currently, https://github.com/BroadbandForum/device-data-model/blob/master/device2/tr-181-2-mqtt.xml contains this:
````
use a random value between
{{param}}*({{param|ConnectRetryIntervalMultiplier}}/1000)^(n-1) and
{{param}}*({{param|ConnectRetryIntervalMultiplier}}/1000)^n for the
connect retry time
````
the `^` are the problem here: the formatting renderer requires an opening and an ending tag: so the superscript formatting is apply to the next formula and ends where the second `^` is found:
![image](https://github.com/BroadbandForum/device-data-model/assets/57828010/0b522574-f230-4ce7-b0dc-ddc72e9635fa)

This could be the solution:
````
use a random value between
{{param}}*({{param|ConnectRetryIntervalMultiplier}}/1000)^(n-1)^ and
{{param}}*({{param|ConnectRetryIntervalMultiplier}}/1000)^n^ for the
connect retry time
````
or you simply write the math formulae in "noformat" style, if it is supported by the HTML renderer.

**Comment by wlupton** [comment]
Oops. Yes, thanks! What's happened is that these descriptions are now passed through a markdown processor (pandoc), which will process the superscripts (they were previously treated as ordinary text and were left alone).

We'll make sure to fix this in the upcoming Device:2.18 release (and we'll check for any other similar cases). Thanks!

By the way, if you work for a BBF member company, please (if you haven't already done so) do visit our wiki home page and sign up for a tools account. <https://wiki.broadband-forum.org>

**Comment by wlupton** [comment]
BBF members with tools accounts will be able to find the internal issue at <https://issues.broadband-forum.org/browse/DEV2DM-1054>.

**Comment by anderewrey** [comment]
thanks @wlupton 

AJC
